/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 FirstModel.gltf 
Author: peterthanh84.tl (https://sketchfab.com/peterthanh84.tl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/art-frame-25b86d7272e849f0967149243601bcbf
Title: Art Frame
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/FirstModel.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials['06___Default']} />
    </group>
  )
}

useGLTF.preload('/FirstModel.gltf')
